### ISSUE TITLE
Disable Reeds in REI / EMI / JEI If the mod isn't installed

### ISSUE THREAD

**Issue by CassieRoseZA** [skniro/GrowableOres#7]
Please can you disable the reeds if the mod isn't installed:
Example: If Thermal isn't installed Disabled the reed completely

**Comment by piotao** [comment]
This feature is very needed, because without it mod is SPAMMING like crazy in logs, causing LOTS of errors (which really should be at most warnings).
Also it will be nice to have a possibility to disable mod in config - because MAYBE someone do not want to have some reeds at all, still having some mods installed. Please implement such nice features for 1.20.1 and up. Also, THANK YOU for this wonderful mod! It is amazing!

**Comment by skniro** [comment]
I make it in 1.20.1exp brunch.You can try to build it by your yourself or use GitHub actions.This version have some big change, so may need long time to release.

**Comment by CassieRoseZA** [comment]
And also don't include mods that aren't for that modloacer

**Comment by skniro** [comment]
> And also don't include mods that aren't for that modloacer

Try 2.0.1-alpha1 version. Changing the config value to false.It should fix this issue.

**Comment by piotao** [comment]
Thanks for your work, I something wrong occurs I write again.

**Comment by CassieRoseZA** [comment]
Still doesn't do anything after setting config to false there's still forge mod reeds showing on REI even tho its a FABRIC MOD
